baseURL = 'https://falak.com'
languageCode = 'en-us'
title = 'Falak: The Inclusity Club'
theme = 'ananke2'
resourceDir = "resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Falak"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
custom_css = ["palate.css", "animations.css"]
text_color = ""
author = ""
navClasses = ""
favicon = "Falak_Logo.png"
site_logo = ""
description = "The Inclusity Club"
body_classes = ""
header_class = "height75"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "custom_color5"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "contain custom_color5 bg-center imageAnimation"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "transparent"
nav_dimming_class = "bg-black-20"
recent_posts_number = 1


[params.ananke.social.share]
networks = [
  "email",
  "instagram"
]

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "email",
  "instagram"
]

[params.ananke.social.instagram]
username = "falak_upes"
[params.ananke.social.email]
username = "falak.upes@stu.upes.ac.in"

[[ananke.social.networks]]
slug = "email1"
label = "email1"
color = "#0077b5"
profile = "mailto:%s"
icon = "linkedin" # font awesome brand icon name
link = "https://www.linkedin.com/shareArticle"
#separator = "&"
