baseURL = 'https://kshitijchandrakar.github.io/FalakSite/'
languageCode = 'en-us'
title = 'Falak: The Inclusity Club'
theme = 'ananke2'
resourceDir = "resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Falak"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
custom_css = ["palate.css", "animations.css", "EventsStyles.css"]
custom_js = ["redirectScriptColor.js"]
text_color = ""
author = ""
navClasses = ""
favicon = "Falak_Logo.png"
site_logo = "Falak_Logo.png"
description = "The Inclusity Club"
body_classes = "custom_color2"
main_classes = "avenir bg-near-white pb3 pt3"
header_class = "height75 height-fit-content"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "transparent"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "h-auto transparent center db coverHeader"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "transparent"
nav_dimming_class = "bg-black-20"
recent_posts_number = 1
mainSections = "blog"


[params.ananke.social.share]
networks = [
  "email",
  "instagram"
]

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "email",
  "instagram",
  "linkedin"
]

[params.ananke.social.linkedin]
username="company/falak-upes"
[params.ananke.social.instagram]
username = "falak_upes"
[params.ananke.social.email]
username = "falak.upes@stu.upes.ac.in"


sectionPagesMenu = 'main2'

[menus]
  [[menus.main2]]
    name = 'About'
    pageRef = '/About'
  [[menus.main2]]
    name = 'Newsletter'
    pageRef = '/Newsletter'
  [[menus.main2]]
    name = 'Events'
    pageRef = '/Events'
  [[menus.main2]]
    name = 'Blog'
    pageRef = '/blog'
  [[menus.main2]]
    name = 'Resources'
    pageRef = '/Resources'
